const Professors = [
  {
    id: "1",
    fname: "John",
    lname: "Zoe",
    school: "Towson University",
    dept: ["Computer & Information Science"],
    lecture: 10,
    textbook: 50,
    likes: 50,
    dislikes: 10,
  },
  {
    id: "2",
    fname: "Mia",
    lname: "Johns",
    school: "Towson University",
    dept: ["Computer & Information Science", "Mathematics"],
    lecture: 25,
    textbook: 10,
    likes: 30,
    dislikes: 10,
  },
  {
    id: "3",
    fname: "Kiki",
    lname: "Wolf",
    school: "Pacific University",
    dept: ["Art"],
    lecture: 20,
    textbook: 2,
    likes: 15,
    dislikes: 5,
  },
  {
    id: "4",
    fname: "Thomas",
    lname: "Stiles",
    school: "Pacific University",
    dept: ["History"],
    lecture: 0,
    textbook: 0,
    likes: 0,
    dislikes: 0,
  },
  {
    id: "5",
    fname: "Autumn",
    lname: "Leeves",
    school: "Pacific University",
    dept: ["Chemistry"],
    lecture: 10,
    textbook: 10,
    likes: 12,
    dislikes: 8,
  },
];

export { Professors };
